# Generated by Django 5.2.8 on 2025-12-04 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subtopic",
            old_name="name",
            new_name="title",
        ),
    ]
