# Generated by Django 5.2.8 on 2025-12-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_rename_name_subtopic_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="pdf",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
