# Generated by Django 5.2.8 on 2025-12-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0003_pdf_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pdf",
            name="file",
            field=models.FileField(upload_to="course_files/"),
        ),
    ]
